### ISSUE TITLE
Multiple users working on the same theme

### ISSUE THREAD

**Issue by francisneedham** [DynamoMTL/shopify-pipeline#95]
Hi,
any suggestions on what is the best way to optimize the workflow inside a developers team? 

thanks !

**Comment by nddery** [comment]
Since you can't have a fully local Shopify environment, what we do at Dynamo is create multiple theme on a single Shopify store and each publish to our own theme. So in our `config/shopify.yml` we declare multiple environments, where only the `theme_id` changes.

```yaml
# config/shopify.yml
my_own_theme
  api_key: 1234567890
  password: 1234567890
  theme_id: your_own_theme_id
  store: 1234567890

my_coworker_theme
  api_key: 1234567890
  password: 1234567890
  theme_id: your_coworker_theme_id
  store: 1234567890
```

And then specify the `env` when running commands, like so:

```
$ yarn serve -- --env=my_own_theme
```
